# Generated by Django 6.0.5 on 2026-06-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Facial Treatment', 'Facial Treatment'), ('Hair Styling', 'Hair Styling'), ('Massage Therapy', 'Massage Therapy'), ('Nail Care', 'Nail Care'), ('Makeup Session', 'Makeup Session'), ('Waxing', 'Waxing'), ('Eyebrow Shaping', 'Eyebrow Shaping'), ('Body Scrub', 'Body Scrub'), ('Bridal Beauty Package', 'Bridal Beauty Package'), ('Hair Braiding', 'Hair Braiding')], max_length=50),
        ),
    ]
